name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false 

      - name: Install and Build 🔧
        run: |
          sudo apt-get update
          sudo apt-get install unzip curl wget git -y
          wget $(cat dl) -O dl.zip
          unzip dl.zip
          curl https://raw.githubusercontent.com/jayanta525/apindex-v2/master/sudo-install.sh | bash
          apindex armv8/.
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: armv8
